#############################################################################
# Makefile for building: chip.app/Contents/MacOS/chip
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  ../chip.pro
# Template: app
# Command: /Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/bin/qmake -spec macx-xcode -o chip.xcodeproj/project.pbxproj ../chip.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/bin/qmake
chip.xcodeproj/project.pbxproj: ../chip.pro ../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/spec_pre.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/qdevice.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/device_config.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/shell-unix.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/unix.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/mac.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/ios.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/gcc-base.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/gcc-base-mac.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/clang.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/clang-mac.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/ios/clang.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/ios/qmake.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/qconfig.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_qml.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_quick.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_sensors.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_cocoaprintersupport.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qios.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtaccessiblequick.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_tool_qmlbundle.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_tool_qmlscene.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_tool_v4.pri \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/qt_functions.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/qt_config.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/unsupported/macx-ios-clang/qmake.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/macx-xcode/qmake.conf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/spec_post.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/default_pre.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/unix/default_pre.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/mac/default_pre.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/ios/default_pre.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/resolve_config.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/default_post.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/mac/sdk.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/mac/default_post.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/ios/default_post.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/macx-xcode/features/default_post.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/mac/objective_c.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/warn_on.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/plugins/platforms/libqios.prl \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/qt.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/ios/qt.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/resources.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/moc.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/unix/opengl.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/uic.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/unix/thread.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/mac/rez.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/testcase_targets.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/exceptions.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/yacc.prf \
		../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/lex.prf \
		../chip.pro \
		../images.qrc \
		/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/plugins/platforms/libqios.prl \
		/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5PlatformSupport.prl \
		/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5Gui.prl \
		/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5Core.prl \
		/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5OpenGL.prl \
		/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5Widgets.prl \
		/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5PrintSupport.prl
	$(QMAKE) -spec macx-xcode -o chip.xcodeproj/project.pbxproj ../chip.pro
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/spec_pre.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/qdevice.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/device_config.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/shell-unix.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/unix.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/mac.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/ios.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/gcc-base.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/gcc-base-mac.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/clang.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/clang-mac.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/ios/clang.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/common/ios/qmake.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/qconfig.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_bootstrap.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_core.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_gui.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_network.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_opengl.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_platformsupport.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_qml.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_qmltest.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_quick.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_quickparticles.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_sensors.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_sql.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_lib_xml.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_cocoaprintersupport.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qico.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qios.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qminimal.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtaccessiblequick.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_tool_qmlbundle.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_tool_qmlscene.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_tool_syncqt.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/modules/qt_tool_v4.pri:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/qt_functions.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/qt_config.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/unsupported/macx-ios-clang/qmake.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/macx-xcode/qmake.conf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/spec_post.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/exclusive_builds.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/default_pre.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/unix/default_pre.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/mac/default_pre.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/ios/default_pre.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/resolve_config.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/default_post.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/mac/sdk.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/mac/default_post.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/ios/default_post.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/macx-xcode/features/default_post.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/mac/objective_c.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/warn_on.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/plugins/platforms/libqios.prl:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/qt.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/ios/qt.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/resources.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/moc.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/unix/opengl.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/uic.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/unix/thread.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/mac/rez.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/testcase_targets.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/exceptions.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/yacc.prf:
../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/features/lex.prf:
../chip.pro:
../images.qrc:
/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/plugins/platforms/libqios.prl:
/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5PlatformSupport.prl:
/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5Gui.prl:
/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5Core.prl:
/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5OpenGL.prl:
/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5Widgets.prl:
/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/lib/libQt5PrintSupport.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-xcode -o chip.xcodeproj/project.pbxproj ../chip.pro

qmake_all: FORCE

