#############################################################################
# Makefile for building: chip.app/Contents/MacOS/chip
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  chip.pro
# Template: app
# Command: /Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/bin/qmake -spec macx-xcode -o chip.xcodeproj/project.pbxproj chip.pro
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/bin/moc
UIC       = /Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DDARWIN_NO_CARBON -DQT_NO_CORESERVICES -DQT_NO_PRINTER -DQT_NO_PRINTDIALOG -Dmain=qt_user_main -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I../../../../qt-src/qt-5x-ios-dev/qtbase/mkspecs/macx-xcode -I. -I/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/mkspecs/unsupported/macx-ios-clang/ios -I../../../../qt-src/qt-5x-ios-dev/qtbase/include -I../../../../qt-src/qt-5x-ios-dev/qtbase/include/QtOpenGL -I../../../../qt-src/qt-5x-ios-dev/qtbase/include/QtPrintSupport -I../../../../qt-src/qt-5x-ios-dev/qtbase/include/QtWidgets -I../../../../qt-src/qt-5x-ios-dev/qtbase/include/QtGui -I../../../../qt-src/qt-5x-ios-dev/qtbase/include/QtCore -I. -I.
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compilers: ./qrc_images.cpp ./moc_mainwindow.cpp ./moc_view.cpp
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: ../images.qrc
	/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/bin/rcc -name images ../images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_view.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_view.cpp
moc_mainwindow.cpp: ../../../../qt-src/qt-5x-ios-dev/qtbase/include/QtWidgets/QWidget \
		../mainwindow.h
	/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include/c++/4.0.0 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/4.2/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include ../mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: ../../../../qt-src/qt-5x-ios-dev/qtbase/include/QtWidgets/QFrame \
		../../../../qt-src/qt-5x-ios-dev/qtbase/include/QtWidgets/QGraphicsView \
		../view.h
	/Users/richard/code/qt-src/qt-5x-ios-dev/qtbase/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include/c++/4.0.0 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/4.2/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include ../view.h -o moc_view.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

